import {CARS} from '../Actions/types';

const initialState =[
        {
          id:0,
          brand:"Mercedes-Benz",
          model:"CLS W218",
          year:2016,
          mileage:67200,
          price:174990,
          fuel:"Benzin",
          imageLogo:'https://i.ibb.co/crrX7tJ/mercedes-benz-logo.png',
          image1:'https://i.ibb.co/RbwPhfc/main.png',
          imageDetail1:'https://i.ibb.co/QQYCWFZ/main.png',
          imageDetail2:'https://i.ibb.co/gJ34Jxb/side1.png',
          imageDetail3:'https://i.ibb.co/4P00smf/side2.png',
          imageDetail4:'https://i.ibb.co/4P00smf/side2.png',
          imageDetail5:'https://i.ibb.co/4P00smf/side2.png',
          power:408,
          fuelConsumption: "11 l/100",
          displacement:4663,
          cylinders: "8",
          color:"Black",
          gearBox:"Automatic",
          gears: "7",
          driveChain:"4x4"
        },
        {
          id:1,
          brand:"Mercedes-Benz",
          model:"CLS W219",
          year:2007,
          mileage:199217,
          price:39999,
          fuel:"Benzin",
          imageLogo:'https://i.ibb.co/crrX7tJ/mercedes-benz-logo.png',
          image1:'https://i.ibb.co/Fhsw4wG/main.png',
          imageDetail1:'https://i.ibb.co/zrbpyDs/side1.png',
          imageDetail2:'https://i.ibb.co/0GRFz3j/side2.png',
          power:388,
          fuelConsumption: "11 l/100",
          displacement:5461,
          cylinders: "8",
          color:"Black",
          gearBox:"Automatic",
          gears: "7",
          driveChain:"Rear"
        
        },
        {
          id:2,
          brand:"Opel",
          model:"Astra GTC",
          year:2005,
          mileage:257811,
          price:11999,
          fuel:"LPG",
          imageLogo:'https://i.ibb.co/9h0vKtg/opel-logo.png',
          image1:'https://i.ibb.co/vQfNNjG/main.jpg',
          imageDetail1:'https://i.ibb.co/6FqTMdD/side1.jpg',
          imageDetail2:'https://i.ibb.co/YLts3rc/side2.jpg',
          power:125,
          fuelConsumption: "9 l/100",
          displacement:1796,
          cylinders: "4",
          color:"Panacotta",
          gearBox:"Manual",
          gears: "5",
          driveChain:"Front"
        },
        {
          id:3,
          brand:"BMW",
          model:"M3 F80",
          year:2015,
          mileage:"50 300 km",
          price:175000,
          fuel:"Benzin",
          image1:'car4/main',
          image2:"car4/side1",
          image3:"car4/side2",
          power:479,
          displacement:2979,
          cylinders: "6",
          color:"White",
          gearBox:"Automatic",
          gears: "7",
          driveChain:"Rear"
        },
        {
          id:4,
          brand:"Kia",
          model:"Stinger",
          year:2019,
          mileage:"500 km",
          price:210900,
          fuel:"Benzin",
          image1:'car5/main',
          image2:"car5/side1",
          image3:"car5/side2",
          power:366,
          displacement:3342,
          cylinders: "6",
          color:"White",
          gearBox:"Automatic",
          gears: "8",
          driveChain:"Rear"
      
        },
        {
          id:5,
          brand:"BMW",
          model:"7 Series",
          year:2018,
          mileage:"16 500 km",
          price:399999,
          fuel:"Diesel",
          image1:'car6/main',
          image2:"car6/side1",
          image3:"car6/side2",
          power:400,
          displacement:2993,
          cylinders: "6",
          color:"Black",
          gearBox:"Automatic",
          gears: "8",
          driveChain:"4x4"
      
        },
        {
          id:6,
          brand:"Lexus",
          model:"LS",
          year:2017,
          mileage:"59 900 km",
          price:399999,
          fuel:"Hybrid",
          image1:'car7/main',
          image2:"car7/side1",
          image3:"car7/side2",
          power:300,
          displacement:3456,
          cylinders: "6",
          color:"Black",
          gearBox:"Automatic",
          gears: "8",
          driveChain:"4x4"
      
        },
        {
          id:7,
          brand:"Audi",
          model:"RS7",
          year:2016,
          mileage:"19 900 km",
          price:399999,
          fuel:"Benzin",
          image1:'car8/main',
          image2:"car8/side1",
          image3:"car8/side2",
          power:605,
          displacement:3993,
          cylinders: "8",
          color:"Blue",
          gearBox:"Automatic",
          gears: "8",
          driveChain:"4x4"
      
        },
      ];


      /*const initialState =[
        {
          id:"0",
          brand:"Mercedes-Benz",
          model:"CLS W218",
          year:2016,
          mileage:"67 200 km",
          price:174990,
          fuel:"Benzin",
          image1:'car1/main',
          image2:'car1/side1',
          image3:'car1/side2',
          power:408,
          displacement:"4 663 cm3",
          cylinders: "8",
          color:"Black",
          gearBox:"Automatic",
          gears: "7",
          driveChain:"4x4"
        },
        {
          id:"1",
          brand:"Mercedes-Benz",
          model:"CLS W219",
          year:2007,
          mileage:"199 217 km",
          price:39999,
          fuel:"Benzin",
          image1:'car2/main',
          image2:"car2/side1",
          image3:"car2/side2",
          power:388,
          displacement:"5 461 cm3",
          cylinders: "8",
          color:"Black",
          gearBox:"Automatic",
          gears: "7",
          driveChain:"Rear"
        
        },
        {
          id:"2",
          brand:"Opel",
          model:"Astra GTC",
          year:2005,
          mileage:"257 811 km",
          price:11999,
          fuel:"Benzin/LPG",
          image1:'car3/main',
          image2:"car3/side1",
          image3:"car3/side2",
          power:125,
          displacement:"1796 cc",
          cylinders: "4",
          color:"Panacotta",
          gearBox:"Manual",
          gears: "5",
          driveChain:"Front"
        },
        {
          id:"3",
          brand:"BMW",
          model:"M3 F80",
          year:2015,
          mileage:"50 300 km",
          price:175000,
          fuel:"Benzin",
          image1:'car4/main',
          image2:"car4/side1",
          image3:"car4/side2",
          power:479,
          displacement:"2 979 cm3",
          cylinders: "6",
          color:"White",
          gearBox:"Automatic",
          gears: "7",
          driveChain:"Rear"
        },
        {
          id:"4",
          brand:"Kia",
          model:"Stinger",
          year:2019,
          mileage:"500 km",
          price:210900,
          fuel:"Benzin",
          image1:'car5/main',
          image2:"car5/side1",
          image3:"car5/side2",
          power:366,
          displacement:"3 342 cm3",
          cylinders: "6",
          color:"White",
          gearBox:"Automatic",
          gears: "8",
          driveChain:"Rear"
      
        },
        {
          id:"5",
          brand:"BMW",
          model:"7 Series",
          year:2018,
          mileage:"16 500 km",
          price:399999,
          fuel:"Diesel",
          image1:'car6/main',
          image2:"car6/side1",
          image3:"car6/side2",
          power:400,
          displacement:"2 993 cm3",
          cylinders: "6",
          color:"Black",
          gearBox:"Automatic",
          gears: "8",
          driveChain:"4x4"
      
        },
        {
          id:"6",
          brand:"Lexus",
          model:"LS",
          year:2017,
          mileage:"59 900 km",
          price:399999,
          fuel:"Hybrid",
          image1:'car7/main',
          image2:"car7/side1",
          image3:"car7/side2",
          power:300,
          displacement:"3 456 cm3",
          cylinders: "6",
          color:"Black",
          gearBox:"Automatic",
          gears: "8",
          driveChain:"4x4"
      
        },
        {
          id:"7",
          brand:"Audi",
          model:"RS7",
          year:2016,
          mileage:"19 900 km",
          price:399999,
          fuel:"Benzin",
          image1:'car8/main',
          image2:"car8/side1",
          image3:"car8/side2",
          power:605,
          displacement:"3 993 cm3",
          cylinders: "8",
          color:"Blue",
          gearBox:"Automatic",
          gears: "8",
          driveChain:"4x4"
      
        },
      ];*/
export default function(state = initialState, action) {

  switch (action.type) {
    case  CARS:
      return {
        ...state,
        cars:action.payload
      }
      default: 
      return state;
  }
}